name: JS/TS Automations
description: Create Home Assistant automations using JavaScript/Typescript.
version: 0.1.0
slug: ha_js_automations
init: false
ingress: true
homeassistant_api: true
arch:
  - aarch64
  - amd64
map:
  - type: addon_config
    read_only: false
    path: /automations/main/scripts
options:
  npm_packages: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  npm_packages:
    - str
image: ghcr.io/lalexdotcom/{arch}-js-automations
